version: '3.8'

services:
  php:
    build: ./.docker/php
    tty: true
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - composer-vendor:/var/www/html/vendor

volumes:
  composer-vendor:
