services:
  Chozetsu\Ch07\FizzBuzz\App\FizzBuzzSequencePrinter:
    public: true
    arguments:
      $fizzBuzz: '@Chozetsu\Ch07\FizzBuzz\Core\NumberConverter'
      $output: '@Chozetsu\Ch07\FizzBuzz\App\OutputInterface'

  Chozetsu\Ch07\FizzBuzz\Core\NumberConverter:
    arguments:
      $rules:
        - '@fizzbuzz.rule.fizz'
        - '@fizzbuzz.rule.buzz'
        - '@Chozetsu\Ch07\FizzBuzz\Spec\PassThroughRule'

  fizzbuzz.rule.fizz:
    class: Chozetsu\Ch07\FizzBuzz\Spec\CyclicNumberRule
    arguments: [ 3, 'Fizz' ]

  fizzbuzz.rule.buzz:
    class: Chozetsu\Ch07\FizzBuzz\Spec\CyclicNumberRule
    arguments: [ 5, 'Buzz' ]

  Chozetsu\Ch07\FizzBuzz\Spec\PassThroughRule: ~

  Chozetsu\Ch07\FizzBuzz\App\OutputInterface:
    class: Chozetsu\Ch07\FizzBuzz\ConsoleOutput
