services:
  _defaults:
    autowire: true

  Chozetsu\Ch07\:
    resource: '../../src/Ch07/*'

  Chozetsu\Ch07\FizzBuzz\App\FizzBuzzSequencePrinter:
    public: true

  Chozetsu\Ch07\FizzBuzz\Core\NumberConverter:
    arguments:
      $rules:
        - '@fizzbuzz.rule.fizz'
        - '@fizzbuzz.rule.buzz'
        - '@Chozetsu\Ch07\FizzBuzz\Spec\PassThroughRule'

  fizzbuzz.rule.fizz:
    class: Chozetsu\Ch07\FizzBuzz\Spec\CyclicNumberRule
    arguments: [ 3, 'Fizz' ]

  fizzbuzz.rule.buzz:
    class: Chozetsu\Ch07\FizzBuzz\Spec\CyclicNumberRule
    arguments: [ 5, 'Buzz' ]
